// <auto-generated />
using System;
using AgricultureApplicationAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgricultureApplicationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgricultureApplicationAPI.Models.FlowersPlantDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Humidity");

                    b.Property<int>("Luminosity");

                    b.Property<string>("Name");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("FlowersPlants");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.ProductChartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTimePost");

                    b.Property<int>("Humidity");

                    b.Property<int>("Luminosity");

                    b.Property<Guid>("ProductId");

                    b.Property<int>("SoilHumidity");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DelayTime");

                    b.Property<string>("Desc");

                    b.Property<int>("Humidity");

                    b.Property<string>("Key");

                    b.Property<int>("Luminosity");

                    b.Property<int>("SoilHumidity");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.UserProjectsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Name");

                    b.Property<Guid>("ProductId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.UserSettingsModel", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HumMaxValue");

                    b.Property<int>("HumMinValue");

                    b.Property<int>("LumMaxValue");

                    b.Property<int>("LumMinValue");

                    b.Property<int>("PlantId");

                    b.Property<int>("PlantType");

                    b.Property<int>("TempMaxValue");

                    b.Property<int>("TempMinValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("ProductId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AgricultureApplicationAPI.Models.VegetablesPlantDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Humidity");

                    b.Property<int>("Luminosity");

                    b.Property<string>("Name");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("VegetablesPlants");
                });
#pragma warning restore 612, 618
        }
    }
}
